# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20170309_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=18, null=True, unique=True),
        ),
    ]
